### ISSUE TITLE
import mlppt error

### ISSUE THREAD

**Issue by qindan2008** [flaport/mplppt#1]
Hi,

After pip3 install mplppt, the package was installed successfully:
_Collecting mplppt
  Downloading mplppt-0.0.0-py3-none-any.whl (25 kB)
Installing collected packages: mplppt
Successfully installed mplppt-0.0.0_

But when import mplppt, error occurred:

_Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mplppt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/mplppt/__init__.py", line 25, in <module>
    from . import shapes
  File "/usr/local/lib/python3.8/dist-packages/mplppt/shapes/__init__.py", line 7, in <module>
    from .base import Object, Group
  File "/usr/local/lib/python3.8/dist-packages/mplppt/shapes/base.py", line 7, in <module>
    from ..new import new
  File "/usr/local/lib/python3.8/dist-packages/mplppt/new.py", line 11, in <module>
    from .templates import PPTXPATH
  File "/usr/local/lib/python3.8/dist-packages/mplppt/templates/__init__.py", line 22, in <module>
    LINE = get_content("line.xml")
  File "/usr/local/lib/python3.8/dist-packages/mplppt/utils/strings.py", line 40, in get_content
    with open(filename, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'line.xml'_

How to resolved the problem?
Thank you very much.

**Comment by flaport** [comment]
Hi @qindan2008 ,

I have updated the package. Please install mplppt>=0.0.5.

Thanks,
Floris

**Comment by qindan2008** [comment]
Thank you.
